name: Scheduled Tasks

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run scheduled script
        run: npm run scheduled-task
