name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint  # Run your linter

  test:
    runs-on: ubuntu-latest
    needs: lint  # This job will run after the lint job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Run your test suite

  build:
    runs-on: ubuntu-latest
    needs: test  # This job will run after the test job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Build your project

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job will run after the build job
    if: github.ref == 'refs/heads/main'  # Only deploy on main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this to your build output directory

  scheduled-task:
    runs-on: ubuntu-latest
    needs: build  # This job will run after the build job
    if: github.event_name == 'schedule'  # Only run on schedule

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run scheduled script
        run: npm run scheduled-task  # Replace with your scheduled task command
